name: Ejecutar scraping cada hora

on:
  schedule:
    - cron: '0 * * * *' # Ejecutar cada hora en el minuto 0
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Paso 3: Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar script de Golem
      - name: Ejecutar scraping Golem
        run: python scraping_golem.py

      # Paso 5: Ejecutar script de Yelmo
      - name: Ejecutar scraping Yelmo
        run: python scraping_yelmo.py

      # Paso 6: Subir cambios al repositorio
      - name: Subir cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Actualizar datos de scraping"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
